name: socket_io
description: Dartlang port of socket.io
version: 0.8.2
author: jumperchen <jumperchen@potix.com>
homepage: https://www.zkoss.org

environment:
  sdk: '>=1.0.0'

dependencies:
  logging: '>=0.11.3+1 <0.12.0'
  stream: '>=1.6.6+1 <2.0.0'
  uuid: '>=0.5.3 <0.6.0'
dev_dependencies:
  unittest: any
  test: '>=0.12.0 <0.13.0'
